# Rights declaration file
# For more information about syntax and structure see here:
# https://github.com/Splamy/TS3AudioBot/wiki/Rights

"+" = [
	"cmd.help", # Basic stuff
	"cmd.pm",
	"cmd.subscribe",
	"cmd.unsubscribe",
	"cmd.kickme",
	
	# Getting song info
	"cmd.link",
	"cmd.song",

	# Conditionals and basic scripting
	"cmd.if",
	"cmd.print",
	"cmd.rng",
	"cmd.eval",
	"cmd.take",
]

# Admin rule
[[rule]]
	# Set your admin Group Ids here
	groupid = [ 0 ]
	# And/Or your admin Client Uids here
	useruid = [ "" ]

	"+" = "*"

# Playing rights
[[rule]]
	# Set Group Ids you want to allow here
	groupid = [ 0 ]
	# And/Or Client Uids here
	useruid = [ "" ]
	# Or remove groupid and useruid to allow for everyone

	"+" = [
		"cmd.play", # Play controls
		"cmd.pause",
		"cmd.stop",
		"cmd.seek",
		"cmd.volume",

		# Playlist management
		"cmd.list.*",
		"cmd.add",
		"cmd.clear",
		"cmd.previous",
		"cmd.next",
		"cmd.random",

		# History features
		"cmd.history.add",
		"cmd.history.from",
		"cmd.history.id",
		"cmd.history.last",
		"cmd.history.play",
		"cmd.history.till",
		"cmd.history.title",
	]

	# Remove this if you want to allow users to save playlist locally
	"-" = [
		"cmd.list.save",
	]