# Rights declaration file
# For more information about syntax and structure see here:
# https://github.com/Splamy/TS3AudioBot/wiki/Rights

"+" = [
	# Basic stuff
	"cmd.help.*",
	"cmd.pm",
	"cmd.subscribe",
	"cmd.unsubscribe",
	"cmd.kickme.*",
	"cmd.version",
	
	# Getting song info
	"cmd.song",
	"cmd.repeat",
	"cmd.random",

	# Conditionals and basic scripting
	"cmd.if",
	"cmd.print",
	"cmd.rng",
	"cmd.eval",
	"cmd.take",
	"cmd.xecute",
	"cmd.getmy.*",
	"cmd.json.*",
	"cmd.bot.use",
	"cmd.rights.can",
]

# Admin rule
[[rule]]
	# Set your admin Group Ids here, ex: [ 13, 42 ]
	groupid = []
	# And/Or your admin Client Uids here
	useruid = [ "_admin_uid_" ]
	# By default treat requests from localhost as admin
	ip = [ "127.0.0.1", "::1" ]

	"+" = "*"

# Playing rights
[[rule]]
	# Set Group Ids you want to allow here, ex: [ 13, 42 ]
	groupid = []
	# And/Or Client Uids here, ex [ "uA0U7t4PBxdJ5TLnarsOHQh4/tY=", "8CnUQzwT/d9nHNeUaed0RPsDxxk=" ]
	useruid = []
	# Or remove groupid and useruid to allow for everyone

	"+" = [
		# Play controls
		"cmd.play",
		"cmd.pause",
		"cmd.stop",
		"cmd.seek",
		"cmd.volume",

		# Playlist management
		"cmd.list.*",
		"cmd.add",
		"cmd.clear",
		"cmd.previous",
		"cmd.next",
		"cmd.random.*",
		"cmd.repeat.*",

		# History features
		"cmd.history.add",
		"cmd.history.from",
		"cmd.history.id",
		"cmd.history.last",
		"cmd.history.play",
		"cmd.history.till",
		"cmd.history.title",
	]

	# Remove this if you want to allow users to save playlist locally
	"-" = [ "cmd.list.save" ]
